### ISSUE TITLE
config.xml missing

### ISSUE THREAD

**Issue by allochi** [GeoNode/geoserver-docker#12]
Hi, 

I followed the instruction, but my docker container exited, and when I check the log I get

```
cp: cannot stat '/geoserver_data/data/security/auth/geonodeAuthProvider/config.xml': No such file or directory
```

Thanks!

**Comment by ojhaujjwal** [comment]
I am getting the same error.

**Comment by ebridger** [comment]
I too get the same error.  This was on macOS 10.12.6 but obviously that was not the problem. Eventually will want to run this on ubuntu 16.04

**Comment by sirtimbly** [comment]
I think this has something to do with https://github.com/GeoNode/data-docker ... on the Readme there I found a link to [GeoServer Data Directory for GeoServer 2.10.x](http://build.geonode.org/geoserver/latest/data-2.10.x.zip) unzipping this into a local directory that is mounted as the /geoserver_data/data volume will make the server start up correctly. 

I recommend updating the docs to include this information.

**Comment by francbartoli** [comment]
Fixed with [7c460624](https://github.com/GeoNode/geoserver-docker/commit/7c460624b79ce8b87fc6ec8455075e72c083cc62)

**Comment by eigood** [comment]
This is not fixed by that commit.  Immediately after those lines in entrypoint.sh, is yet *another* attempt to copy "REST role service" and several other things.

**Comment by francbartoli** [comment]
@eigood REST role service config.xml is something different from this one

**Comment by francbartoli** [comment]
@cdiaz can you tell us which image version you are using? Again did you use to close down the `docker-compose` command with the option `-v` to remove all volumes?

**Comment by danwild** [comment]
I had the same issue trying to use `2.13.x` and `2.14.x`.
Had to grab  GeoNode's expected `data_dir` from https://build.geo-solutions.it/geonode/geoserver/latest/data-2.14.x.zip and mount as volume to make it run.

**Comment by robertd** [comment]
@danwild Can you please post a github gist on how you got this to work? Thanks.

**Comment by francbartoli** [comment]
@danwild @cdiaz this is the situation on the geoserver container from geonode master:

```
root@c497da44e3eb:/usr/local/tomcat/tmp# ls -lart /geoserver_data/data/security/auth/
total 16
drwxr-xr-x 2 root root 4096 Mar 22 10:37 geofence
drwxr-xr-x 2 root root 4096 Mar 22 10:37 default
drwxr-xr-x 4 root root 4096 Mar 22 10:37 .
drwxr-xr-x 8 root root 4096 Mar 22 10:37 .. 
```

I think your are using an old data directory mounted in there. The folder you are looking for doesn't exist anymore

**Comment by drnextgis** [comment]
I faced with the same issue. It also was reported and closed here https://github.com/GeoNode/geoserver-docker/issues/30. But in the end it is not clear what is the right command should be used for start container.

**Comment by francbartoli** [comment]
@drnextgis can you clarify a bit further what do you mean with the right command to start a container? If you have a look at the https://github.com/GeoNode/geonode/blob/master/docker-compose.yml you would start the stack with `docker-compose up -d`.
In case you want to start just this container then it's up to you to translate the docker-compose syntax of the geoserver portion into a `docker run ...`

**Comment by drnextgis** [comment]
@francbartoli thanks for quick reply. After careful reading the documentation I came up with the following solution:

1. Download data-2.15.x.zip from [here](https://build.geo-solutions.it/geonode/geoserver/latest/) (filename depends on GeoServer version used in Dockerfile)
2. Extract archive (in my case in `/opt/geoserver_data/data`)
3. Start container:
```
docker run --name "geoserver" -v /var/run/docker.sock:/var/run/docker.sock \
                              -v /opt/geoserver_data/data:/geoserver_data/data \
                              -p 8080:8080 geonode/geoserver
```

All this information is in the docs already. I just was a little bit confused about quickstart command doesn't work.

**Comment by francbartoli** [comment]
Glad you have solved
