### ISSUE TITLE
GeoServer 2.12.x fails to start with creepy error

### ISSUE THREAD

**Issue by cezio** [GeoNode/geoserver-docker#17]
Dockerized GS may fail to deploy in tomcat with exception:

> Caused by: java.lang.IllegalStateException: Unable to complete the scan for annotations for web application [/geoserver] due to a StackOverflowError. Possible root causes include a too low setting for -Xss and illegal cyclic inheritance dependencies. The class hierarchy being processed was [org.bouncycastle.asn1.ASN1EncodableVector->org.bouncycastle.asn1.DEREncodableVector->org.bouncycastle.asn1.ASN1EncodableVector]

related: https://stackoverflow.com/questions/29955410/how-do-i-fix-stackoverflowerror-in-org-apache-catalina-startup-contextconfig-pop

The fix is to set

`org.apache.catalina.startup.ContextConfig.jarsToSkip=bcprov*.jar`

**Comment by francbartoli** [comment]
@cezio have you encountered this error anymore?

**Comment by cezio** [comment]
No, but this is also one of steps in http://docs.geonode.org/en/latest/tutorials/install_and_admin/geonode_install/install_geoserver_application.html?highlight=geoserver#setup-geoserver

**Comment by afabiani** [comment]
fixed
