### ISSUE TITLE
Error when starting 2.13.x

### ISSUE THREAD

**Issue by icemagno** [GeoNode/geoserver-docker#30]
`cp: cannot stat '/geoserver_data/data/security/role/geonode REST role service/config.xml': No such file or directory`

```
docker run --name atlasgeo --hostname atlasgeo \
--network terena \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /opt/atlasgeo:/geoserver_data/data \
-p 36402:8080 \
-d geonode/geoserver:2.13.x
```

**Comment by afabiani** [comment]
The GeoServer Data Dir Volume must be pass through the Environment variable

VOLUME $GEOSERVER_DATA_DIR

**Comment by francbartoli** [comment]
I'm assuming we can close this. Can you confirm @icemagno?

**Comment by icemagno** [comment]
Well I have no time to test it now but what you said makes sense so you can close.
