### ISSUE TITLE
ECW

### ISSUE THREAD

**Issue by oiacrasec** [GeoNode/geoserver-docker#58]
Do you have any dockerfile to install geoserver + ECW?

**Comment by gannebamm** [comment]
This is an example dockerfile I use in conjunction with SPC Geonode to load community plugins into Geoserver docker:

https://gist.github.com/gannebamm/5ad151dfbac5066bca42f935e1110d7c

**Beware:** It is possibly outdated

**Comment by oiacrasec** [comment]
Thank you!

**Comment by gannebamm** [comment]
@oiacrasec can we close this issue?

**Comment by oiacrasec** [comment]
Yes
