### ISSUE TITLE
Layer doesn't show up if admin is logged out

### ISSUE THREAD

**Issue by alxcost** [GeoNode/geoserver-docker#74]
Hi,

I imported a shapefile successfully to Geoserver.

When I query the WMS service for its capabilities, i.e., `https://<domain>/geoserver/ows?service=wms&version=1.3.0&request=GetCapabilities`
The layer itself and all its capabilities show up fine, but only if the user is logged in as admin.
If the user is logged out (or if I try to access the service through a another browser, a private window, etc...), the Layer simply doesn't seem to show up.

A more specific example,
When I specifically query for the layer while having an admin session, i.e. `https://<domain>/geoserver/wms?service=WMS&version=1.1.0&request=GetMap&layers=<my layer> [other parameters ommitted for brevity]`
The layer is shown just fine.
If the user is logged out, I get the error `Could not find layer`.

Does anyone have any idea what could be causing this? Is there any privacy parameter that I might have overlooked? Any specific Docker parameter that I missed? I ask this because this doesn't seem to happen with my other non-Docker deployment.

Thank you!

**Comment by giohappy** [comment]
@alxcost a basic question: is the layer view permission configured for "Anyone"?

**Comment by alxcost** [comment]
Hello @giohappy, 

I checked `security/layer.properties` (~which has its default settings~) and they seem to be:
```
#Thu May 20 10:14:42 GMT 2021
*.*.r=*
*.*.w=GROUP_ADMIN,ADMIN
mode=MIXED
```

Which I think means "Anyone" can read, right?

Also: 
My settings are based on `data-2.18.3.zip` from https://build.geo-solutions.it/geonode/geoserver/latest/

**Comment by giohappy** [comment]
oh wait, I thought you were talking about GeoNode, since this is the docker repo for Geoserver for GeoNode.
Questions related to Geoserver itself should be asked on the Geoserver [channels](http://geoserver.org/comm/).

**Comment by alxcost** [comment]
Ah, got it, thanks. I'll share my question there.
