### ISSUE TITLE
Geofence build prevents layer upload

### ISSUE THREAD

**Issue by t-book** [GeoNode/geoserver-docker#75]
Running geonode 3.2 on geonode project docker fails on layer upload. The same is happening when one tries to publish a layer in geoserver gui. The stack trace https://hastebin.com/xilupocuri.apache indicates that something is wrong with geofence. Further debugging shows that yesterdays jars work:

```
-rw-r--r--  1 csgis csgis  85436 Jun  7 16:12 gs-geofence-2.18-20210225.223638-83.jar
-rw-r--r--  1 csgis csgis 112311 Jun  7 16:12 gs-geofence-server-2.18-20210225.224053-83.jar
```
while those from today fail 
```
-rw-r--r--  1 docker docker  89162 Mai 24 19:41 gs-geofence-2.18-20210517.135648-138.jar
-rw-r--r--  1 docker docker 114610 Mai 24 19:41 gs-geofence-server-2.18-20210517.140149-138.jar
```

**Comment by afabiani** [comment]
Depends on: https://osgeo-org.atlassian.net/browse/GEOS-10094

**Comment by afabiani** [comment]
@t-book JIRA fixed and WAR regenerated. Close at your convenience.
