### ISSUE TITLE
[Security][Geoserver][2.17.2] Upgrade Geoserver Tomcat Image to the latest minor release

### ISSUE THREAD

**Issue by malnajdi** [GeoNode/geoserver-docker#76]
Greeting Team, 

Usually security teams in every company would do a vulnerability scan on each server.
I wanted to upgrade the base image somehow to be able to close these vulnerabilities. 

List can be found here: https://tomcat.apache.org/security-9.html#Apache_Tomcat_9.x_vulnerabilities

Just an idea, isn't there a way to always upgrade the minor version like 9.0.* ? 

Thanks.

**Comment by t-book** [comment]
> Just an idea, isn't there a way to always upgrade the minor version like 9.0.* ?

I think in this case we would need to change the image to not use the base from docker hub but build tomcat on our own.
What do you think @giohappy @afabiani

**Comment by malnajdi** [comment]
@t-book if we have to do this our own, i will have to clone this repo and build a docker image and upload it and use it in my project right ?

**Comment by malnajdi** [comment]
Hi team, 

Any update or this ?

**Comment by malnajdi** [comment]
Never mind, i built my own image and published it.
Thanks a lot
