### ISSUE TITLE
Geonode locales location while using the docker setup

### ISSUE THREAD

**Issue by kenseii** [GeoNode/geoserver-docker#79]
Hello,

Where are the locales located on an environment set up using this repository?
I am trying to access this file https://github.com/GeoNode/geonode/blob/master/geonode/locale/ja/LC_MESSAGES/djangojs.po but i cant locate it on the machine nor inside the the containers.

Is there any part of the documentation that would provide some guidance?

**Comment by t-book** [comment]
Sure! https://docs.geonode.org/en/master/contribute/translation/index.html?highlight=translation
By the way you're in the repository for the geoserver image ;) Might fit better in the django context as geoserver does not care at all about djangos po files. Visit the Dockerfile of the Django service to see where geonode is istalled. (Differs between geonode and geonode project) there you'll find the locale folder ...
