### ISSUE TITLE
./entrypoint.sh: line 11: python: command not found

### ISSUE THREAD

**Issue by mwallschlaeger** [GeoNode/geoserver-docker#86]
When running container without DOCKER_HOST_IP set. The python call fails because python is not an alias for python3 in this image. 

Found this in 2.19.6 and also in Master ...

I would suggest replace:

```bash
# old:
echo export DOCKER_HOST_IP=`python /usr/local/tomcat/tmp/get_dockerhost_ip.py` >> /root/.override_env
# new:
echo export DOCKER_HOST_IP=`python3 /usr/local/tomcat/tmp/get_dockerhost_ip.py` >> /root/.override_env
```

**Comment by giohappy** [comment]
you're right @mwallschlaeger. It's been fixed a long time ago for geonode-project, (https://github.com/GeoNode/geonode-project/commit/0e8849d16388c3e776dc8731cde52c9f7a688062) but it's not been fixed here.

**Comment by giohappy** [comment]
@mwallschlaeger I've taken this opportunity to review the publishing workflow of the geoserver images on Docker Hub. The DevOps team at the moment build them from the [geonode-project Docker file](https://github.com/GeoNode/geonode-project/tree/master/docker/geoserver), not from this repo.

We have already planned (https://github.com/GeoNode/geoserver-docker/issues/87) to align this repo to the configuration of geonode-project, and restore the builds from this repo.

**Comment by mwallschlaeger** [comment]
ok, i understand. Additionally i found the same problem on the geonode/geoserver:2.19.6 but i guess its build up from this repo ...
