### ISSUE TITLE
Server busy on delete layer

### ISSUE THREAD

**Issue by t-book** [GeoNode/geoserver-docker#92]
@afabiani 

on a larger instance with over 3k layers (mostly raster) I'm experiencing that geoserver becomes not responding for about 2-3 Minutes when deleting a layer in geonode. The server status of geoserver than shows "Server busy". Do you know of any problem or which process (like invalidating some cache) could lock geoserver for some time?

As always verbose logs are a bit overwhelming with geoserver.

I do see a lot of geofence requests

```
geoserver4geonode  | 26 Mar 11:36:10 DEBUG  [org.geoserver] - Thread 117 got the lock in mode READ
geoserver4geonode  | 26 Mar 11:36:10 DEBUG  [geoserver.geofence] - Getting access limits for workspace geonode
geoserver4geonode  | 26 Mar 11:36:10 DEBUG  [geoserver.geofence] - Admin level access, returning full rights for workspace geonode
geoserver4geonode  | 26 Mar 11:36:10 DEBUG  [geoserver.geofence] - Getting access limits for Resource sbb_kart_16929_blatt_3253_4_sahab_23037
geoserver4geonode  | 26 Mar 11:36:10 DEBUG  [geoserver.geofence] - Admin level access, returning full rights for layer sbb_kart_16929_blatt_3253_4_sahab_23037
geoserver4geonode  | 26 Mar 11:36:10 DEBUG  [geoserver.geofence] - Returning mode HIDE for resource CoverageInfoImpl[sbb_kart_16929_blatt_3253_4_sahab_23037]
geoserver4geonode  | 26 Mar 11:36:10 DEBUG  [geoserver.geofence] - Getting access limits for workspace geonode
geoserver4geonode  | 26 Mar 11:36:10 DEBUG  [geoserver.geofence] - Admin level access, returning full rights for workspace geonode
geoserver4geonode  | 26 Mar 11:36:10 TRACE  [geoserver.platform] - Found Property override: 'GEOSERVER_XSTREAM_WHITELIST' to be unset
geoserver4geonode  | 26 Mar 11:36:10 TRACE  [geoserver.platform] - Found Java environment variable : 'GEOSERVER_XSTREAM_WHITELIST' to be unset
geoserver4geonode  | 26 Mar 11:36:10 TRACE  [geoserver.platform] - Found Servlet context parameter : 'GEOSERVER_XSTREAM_WHITELIST' to be unset
geoserver4geonode  | 26 Mar 11:36:10 TRACE  [geoserver.platform] - Found System environment variable : 'GEOSERVER_XSTREAM_WHITELIST' to be unset
geoserver4geonode  | 26 Mar 11:36:10 TRACE  [geoserver.platform] - Found Property override: 'GEOSERVER_XSTREAM_WHITELIST' to be unset
geoserver4geonode  | 26 Mar 11:36:10 TRACE  [geoserver.platform] - Found Java environment variable : 'GEOSERVER_XSTREAM_WHITELIST' to be unset
geoserver4geonode  | 26 Mar 11:36:10 TRACE  [geoserver.platform] - Found Servlet context parameter : 'GEOSERVER_XSTREAM_WHITELIST' to be unset
geoserver4geonode  | 26 Mar 11:36:10 TRACE  [geoserver.platform] - Found System environment variable : 'GEOSERVER_XSTREAM_WHITELIST' to be unset
geoserver4geonode  | 26 Mar 11:36:10 TRACE  [geoserver.platform] - Found Property override: 'GEOSERVER_XSTREAM_WHITELIST' to be unset
geoserver4geonode  | 26 Mar 11:36:10 TRACE  [geoserver.platform] - Found Java environment variable : 'GEOSERVER_XSTREAM_WHITELIST' to be unset
geoserver4geonode  | 26 Mar 11:36:10 TRACE  [geoserver.platform] - Found Servlet context parameter : 'GEOSERVER_XSTREAM_WHITELIST' to be unset
geoserver4geonode  | 26 Mar 11:36:10 TRACE  [geoserver.platform] - Found System environment variable : 'GEOSERVER_XSTREAM_WHITELIST' to be unset
geoserver4geonode  | 26 Mar 11:36:10 TRACE  [geoserver.platform] - Found Property override: 'PROXY_BASE_URL' to be unset
geoserver4geonode  | 26 Mar 11:36:10 TRACE  [geoserver.platform] - Found Java environment variable : 'PROXY_BASE_URL' to be unset
geoserver4geonode  | 26 Mar 11:36:10 TRACE  [geoserver.platform] - Found Servlet context parameter : 'PROXY_BASE_URL' to be unset
geoserver4geonode  | 26 Mar 11:36:10 TRACE  [geoserver.platform] - Found System environment variable : 'PROXY_BASE_URL' to be unset
geoserver4geonode  | 26 Mar 11:36:10 DEBUG  [geoserver.filters] - Compressing output for mimetype: application/xml
geoserver4geonode  | 26 Mar 11:36:10 DEBUG  [org.geoserver] - Thread 117 locking in mode READ
geoserver4geonode  | 26 Mar 11:36:10 DEBUG  [org.geoserver] - Thread 117 releasing the lock in mode READ
```

Also some WPS Exceptions

```
geoserver4geonode  | 26 Mar 11:36:17 TRACE  [platform.resource] - delta computed in 10ms for /geoserver_data/data/gwc-layers
geoserver4geonode  | 26 Mar 11:36:18 DEBUG  [geoserver.geofence] - Getting access limits for workspace geonode
geoserver4geonode  | 26 Mar 11:36:18 DEBUG  [geoserver.geofence] - Admin level access, returning full rights for workspace geonode
geoserver4geonode  | 26 Mar 11:36:18 DEBUG  [config.impl] - Could not locate service of type interface org.geoserver.wps.WPSInfo in workspace null, available services were []
geoserver4geonode  | 26 Mar 11:36:18 ERROR  [config.impl] - Could not locate service of type interface org.geoserver.wps.WPSInfo, local workspace is null
geoserver4geonode  | 26 Mar 11:36:18 ERROR  [config.impl] - Error occurred processing a configuration change listener
geoserver4geonode  | java.lang.NullPointerException
geoserver4geonode  | 	at org.geoserver.wps.WPSInitializer.initWPS(WPSInitializer.java:79)
geoserver4geonode  | 	at org.geoserver.wps.WPSInitializer$1.handlePostGlobalChange(WPSInitializer.java:71)
```

But cannot find any real cause yet. (Version is gn 4.1.x and geoserver 2.23.x)

**Comment by giohappy** [comment]
I'll let @afabiani answer if he has a more details, but I suspect that the problem is the load on the DB. CRUD operations on datesets are quite heavy in terms of DB operations, and we're experiencing that some do not scale well when the number of layers is in the order of thousands.

Could you take a look to the metrics of your DB while it happens?

**Comment by t-book** [comment]
Thanks a log @giohappy I will have a look at the DB metrics and come back soon.

**Comment by t-book** [comment]
(The strange thing is I don't get this behaviour with GeoNode 3.2.0 and Geoserver 2.20.7)

**Comment by giohappy** [comment]
@t-book are you using the new or the current importer?

**Comment by t-book** [comment]
@giohappy That's a fresh 4.1.x install so I would guess it is the new, right?

https://github.com/GeoNode/geonode/blob/4.1.x/geonode/settings.py#L1056

Can you explain how I would go back to the old, so that I can test if that makes a difference?

**Comment by giohappy** [comment]
@t-book no the new imported must be set up explicitly, it's not activated by default yet. So I assume you're using the current one.

**Comment by t-book** [comment]
@giohappy Is there some readme on how to do it?

**Comment by giohappy** [comment]
>@giohappy Is there some readme on how to do it?

You can follow the README here https://github.com/geosolutions-it/geonode-importer

**Comment by t-book** [comment]
Thanks @giohappy I will give it a try soon and also collect metrics for DB. You probably expect a change based on the different delete method https://github.com/geosolutions-it/geonode-importer/blob/b30cd2e5c82a6433f6d757fd7714068f4b284323/importer/handlers/common/vector.py#L163 ... Lets see if this changes things.

**Comment by afabiani** [comment]
@t-book try to disable the diskquota in the case it is enabled and using a postgresql instance. If that helps that means that probably your DB configuration is a bit understimated in terms of connections and resources available. Tuning up this one really depends on your current architecture and how the system is used.

**Comment by afabiani** [comment]
A tool like [PGTune](https://pgtune.leopard.in.ua/) might help you to tune it up a bit and see if different configurations help to speed up the process.

**Comment by t-book** [comment]
@giohappy @afabiani 

First of all, thanks a lot for your great input. 
Disabling the quota looks like making a H U G E  difference. 
I can't believe it yet (fully), but  db metrics speak volumes:

This is how I tested:

1. Uploaded a geotiff twice
2. enabled full logging in postgres
3. truncate logs
4. used the api (to not spoil logs with frontend requests) to delete first layer 
5. truncate logs
6. disabled quota.
7. deleted second layer
8. compared the log files

#  1 Number of requests
## Quota enabled

![image](https://user-images.githubusercontent.com/20478652/228033443-846a5135-be1e-4213-bdb6-188b95809bb0.png)

## Quota disabled

![image](https://user-images.githubusercontent.com/20478652/228033513-8eb38689-d718-498e-973c-d4c3ab1fb3d1.png)

# 2 Queries by type
## Quota enabled

![image](https://user-images.githubusercontent.com/20478652/228033816-234de5c5-bbc6-4c6b-8306-d26146b0fa98.png)

## Quota disabled

![image](https://user-images.githubusercontent.com/20478652/228033946-3b53462c-5204-44de-a5fa-7e6be6d942c6.png)

_Interesting how the inserts rise ..._

# 3 Most frequent query
## Quota enabled
![image](https://user-images.githubusercontent.com/20478652/228034767-91a2d938-343c-41a7-b3ad-777ece99f2e6.png)

## Quota disabled

![image](https://user-images.githubusercontent.com/20478652/228034820-28e96d7d-4da0-4d1b-848c-466785ef1c7e.png)

# 4 Time consuming queries
## Quota enabled
![image](https://user-images.githubusercontent.com/20478652/228035037-93df74fa-51fb-4dad-aa3f-5d7329a7544d.png)
## Quota disabled
![image](https://user-images.githubusercontent.com/20478652/228035115-b1f07381-732c-4eed-94ea-2682ede73817.png)

---
From a first view it looks the blocked state (server busy) is gone. yeah ! 
I will continue testing with the new uploader.

**Comment by t-book** [comment]
I'm closing here. After several tests disabling the disc quota really solved the problem.

**Comment by giohappy** [comment]
we have plans to analyze better the disk quota configurations and its behavior in the context of GeoNode.
